kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: devspaces
  namespace: openshift-devspaces
spec:
  to:
    kind: Service
    name: che-gateway
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
