kind: Secret
apiVersion: v1
metadata:
  name: repo-1271285356
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
data:
  enableLfs: dHJ1ZQ==
  password: Z2hwX2JGamV4S25LaUpjRjJqT21LRENGQWJZRUExMmlpYTNaZnlCTA==
  project: ZGVmYXVsdA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL1JILVNQUlVDRS1URUFNL3NwcnVjZS1naXRvcHMuZ2l0
  username: ZHZhbmJhbGVu
type: Opaque
