kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"db:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"db\")].image"}]
    openshift.io/generated-by: OpenShiftNewApp
  name: db
  namespace: spruce-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: db
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: db
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: db
          image: >-
            registry.redhat.io/rhel9/postgresql-15@sha256:969b0f80a5c394a802b53fec50008f83880046e2f920b9e829b286bf8f789df9
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: adminpassword
            - name: POSTGRESQL_DATABASE
              value: todos
            - name: POSTGRESQL_PASSWORD
              value: todopassword
            - name: POSTGRESQL_USER
              value: todouser
