kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-pvc
  namespace: spruce-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace-ui-app-source
  namespace: spruce-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem

