kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-image-registry-operator-from-spruce-pipelines-to-spruce-prod
  namespace: spruce-prod
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccount:spruce-pipelines:pipeline'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-image-registry-operator

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-builder-from-spruce-pipelines-to-spruce-prod
  namespace: spruce-prod
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccount:spruce-pipelines:pipeline'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-builder'

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-puller-from-spruce-pipelines-to-spruce-prod
  namespace: spruce-prod
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccount:spruce-pipelines:pipeline'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-pusher-from-spruce-pipelines-to-spruce-prod
  namespace: spruce-prod
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccount:spruce-pipelines:pipeline'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-pusher'

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-image-registry-operator-from-spruce-pipelines-to-spruce-dev
  namespace: spruce-dev
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccount:spruce-pipelines:pipeline'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-image-registry-operator

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-builder-from-spruce-pipelines-to-spruce-dev
  namespace: spruce-dev
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccount:spruce-pipelines:pipeline'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-builder'

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-puller-from-spruce-pipelines-to-spruce-dev
  namespace: spruce-dev
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccount:spruce-pipelines:pipeline'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-pusher-from-spruce-pipelines-to-spruce-dev
  namespace: spruce-dev
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccount:spruce-pipelines:pipeline'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-pusher'

