kind: Secret
apiVersion: v1
metadata:
  name: git-secret
  namespace: spruce-pipelines
  annotations:
    tekton.dev/git-0: github.com
data:
  password: Z2hwX2JGamV4S25LaUpjRjJqT21LRENGQWJZRUExMmlpYTNaZnlCTA==
  username: ZHZhbmJhbGVu
type: kubernetes.io/basic-auth
---
kind: Secret
apiVersion: v1
metadata:
  name: pipeline-tutorial-secret
  namespace: spruce-pipelines
  annotations:
    tekton.dev/git-0: 'https://github.com'
data:
  password: Z2hwX2JGamV4S25LaUpjRjJqT21LRENGQWJZRUExMmlpYTNaZnlCTA==
  username: ZHZhbmJhbGVu
type: kubernetes.io/basic-auth
