kind: Service
apiVersion: v1
metadata:
  name: db
  namespace: spruce-dev
  labels:
    app: db
    app.kubernetes.io/component: db
    app.kubernetes.io/instance: db
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 5432-tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: db
status:
  loadBalancer: {}

